plugins {
    id 'com.android.application'
}

android {
    namespace = "org.libsdl.app"
    compileSdkVersion 35
    ndkVersion = "28.2.13676358"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'x86_64', 'arm64-v8a'
        }
    }

    signingConfigs {
        release {
            // change here your info
            storeFile file("../release-key.jks")
            storePassword "PASS_WORD"
            keyAlias "grngame"
            keyPassword "PASS_WORD"
        }
    }

    buildTypes {
        release {
            minifyEnabled false

            signingConfig signingConfigs.release

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets.main {
        jniLibs.srcDir 'jni/src'
    }

    lint {
        abortOnError = false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
