name: Build iOS

on:
  workflow_call:

jobs:
  build-ios:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]

    runs-on: macos-26
    name: "ios-${{ matrix.arch }} / release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache-ios-${{ matrix.arch }}'
          package-cache: true
          build-cache: true

      - name: Select Xcode
        run: |
          ls /Applications | grep Xcode
          sudo xcode-select -s /Applications/Xcode_26.2.app
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Configure
        run: >
          xmake f -p iphoneos -a ${{ matrix.arch }} -m release -c
          --target_minver=17.5
          --embed_assets=y
          -y -vv

      - name: Build
        run: xmake build -y -vv

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ios-${{ matrix.arch }}-release-embedtrue"
          path: build/Runtime/
          if-no-files-found: error