name: Format

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-24.04
    name: "clang-format"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format 23
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 23

      - name: Check clang-format version
        run: clang-format --version

      - name: Check formatting
        shell: bash
        run: |
          find grngame -type f \( -name '*.c' -o -name '*.h' \) -print0 \
            | xargs -0 -r clang-format --dry-run --Werror